# Generated by Django 3.0.4 on 2020-03-18 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoiOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COM', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('原始图', models.ImageField(height_field='url_height', upload_to='icons', width_field='url_width')),
                ('处理图', models.ImageField(height_field='url_height', upload_to='icons', width_field='url_width')),
                ('ConLen', models.IntegerField(default=0)),
            ],
        ),
    ]
