# Generated by Django 3.0.4 on 2020-03-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0002_auto_20200318_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoios',
            old_name='原始图',
            new_name='Conphoto',
        ),
        migrations.RenameField(
            model_name='autoios',
            old_name='处理图',
            new_name='photo',
        ),
    ]
